<a href="https://colab.research.google.com/github/The-Professor99/ML_Practice/blob/main/hands_on_learning/hands_on_ml_with_scikit-learn_Aurelien_textbook/Chapter_2_End_to_End_ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import tarfile
import urllib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

In [ ]:
def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

In [ ]:
def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)

In [ ]:
# fetch_housing_data()

In [ ]:
housing = load_housing_data()
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [ ]:
# To find out how many categories ocean_proximity has
housing["ocean_proximity"].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [ ]:
# Getting a summary of other numerical attributes
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
%matplotlib

Using matplotlib backend: <object object at 0x7fe5f45fe6f0>

In [ ]:
housing.hist(bins=50, figsize=(20, 15))

array([[<AxesSubplot: title={'center': 'longitude'}>,
        <AxesSubplot: title={'center': 'latitude'}>,
        <AxesSubplot: title={'center': 'housing_median_age'}>],
       [<AxesSubplot: title={'center': 'total_rooms'}>,
        <AxesSubplot: title={'center': 'total_bedrooms'}>,
        <AxesSubplot: title={'center': 'population'}>],
       [<AxesSubplot: title={'center': 'households'}>,
        <AxesSubplot: title={'center': 'median_income'}>,
        <AxesSubplot: title={'center': 'median_house_value'}>]],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42)

In [ ]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4128 entries, 20046 to 3665
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           4128 non-null   float64
 1   latitude            4128 non-null   float64
 2   housing_median_age  4128 non-null   float64
 3   total_rooms         4128 non-null   float64
 4   total_bedrooms      3921 non-null   float64
 5   population          4128 non-null   float64
 6   households          4128 non-null   float64
 7   median_income       4128 non-null   float64
 8   median_house_value  4128 non-null   float64
 9   ocean_proximity     4128 non-null   object
dtypes: float64(9), object(1)
memory usage: 354.8+ KB

In [ ]:
housing["income_cat"] = pd.cut(housing["median_income"], \
                              bins=[0, 1.5, 3, 4.5, 6, np.inf], \
                              labels=[1, 2, 3, 4, 5])

In [ ]:
housing["income_cat"].hist()

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit

In [ ]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    print(train_index, test_index, "otilo")
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

[12655 15502  2908 ... 19263 19140 19773] [ 5241 17352  3505 ... 17223 10786  3965] otilo

In [ ]:
strat_test_set["income_cat"].value_counts() / len(strat_test_set)

3    0.350533
2    0.318798
4    0.176357
5    0.114341
1    0.039971
Name: income_cat, dtype: float64

In [ ]:
for set_ in (strat_train_set, strat_test_set):
    set_.drop("income_cat", axis=1, inplace=True)

In [ ]:
housing = strat_train_set.copy()

In [ ]:
housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.1)

In [ ]:
housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.4, \
            s=housing["population"]/100, label="population", \
            figsize=(10, 7), c="median_house_value", cmap=plt.get_cmap("jet"), colorbar=True)

In [ ]:
corr_matrix = housing.corr()

/tmp/ipykernel_6910/2466220658.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = housing.corr()

In [ ]:
corr_matrix["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.687151
total_rooms           0.135140
housing_median_age    0.114146
households            0.064590
total_bedrooms        0.047781
population           -0.026882
longitude            -0.047466
latitude             -0.142673
Name: median_house_value, dtype: float64

In [ ]:
from pandas.plotting import scatter_matrix
attributes = ["median_house_value", "median_income",
             "total_rooms", "housing_median_age"]
scatter_matrix(housing[attributes])

array([[<AxesSubplot: xlabel='median_house_value', ylabel='median_house_value'>,
        <AxesSubplot: xlabel='median_income', ylabel='median_house_value'>,
        <AxesSubplot: xlabel='total_rooms', ylabel='median_house_value'>,
        <AxesSubplot: xlabel='housing_median_age', ylabel='median_house_value'>],
       [<AxesSubplot: xlabel='median_house_value', ylabel='median_income'>,
        <AxesSubplot: xlabel='median_income', ylabel='median_income'>,
        <AxesSubplot: xlabel='total_rooms', ylabel='median_income'>,
        <AxesSubplot: xlabel='housing_median_age', ylabel='median_income'>],
       [<AxesSubplot: xlabel='median_house_value', ylabel='total_rooms'>,
        <AxesSubplot: xlabel='median_income', ylabel='total_rooms'>,
        <AxesSubplot: xlabel='total_rooms', ylabel='total_rooms'>,
        <AxesSubplot: xlabel='housing_median_age', ylabel='total_rooms'>],
       [<AxesSubplot: xlabel='median_house_value', ylabel='housing_median_age'>,
        <AxesSubplot: xlabel='median_income', ylabel='housing_median_age'>,
        <AxesSubplot: xlabel='total_rooms', ylabel='housing_median_age'>,
        <AxesSubplot: xlabel='housing_median_age', ylabel='housing_median_age'>]],
      dtype=object)

In [ ]:
housing.plot(kind="scatter", x="median_income", y="median_house_value",
            alpha=0.1)

In [ ]:
housing["rooms_per_household"] = housing["total_rooms"]/housing["households"]
housing["bedrooms_per_room"] = housing["total_bedrooms"]/housing["total_rooms"]
housing["population_per_household"] = housing["population"]/housing["households"]

In [ ]:
corr_matrix = housing.corr()
corr_matrix["median_house_value"].sort_values(ascending=False)

/tmp/ipykernel_6910/826279322.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = housing.corr()

median_house_value          1.000000
median_income               0.687151
rooms_per_household         0.146255
total_rooms                 0.135140
housing_median_age          0.114146
households                  0.064590
total_bedrooms              0.047781
population_per_household   -0.021991
population                 -0.026882
longitude                  -0.047466
latitude                   -0.142673
bedrooms_per_room          -0.259952
Name: median_house_value, dtype: float64

## Data Cleaning

In [ ]:
# Get Fresh Data
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

Most Machine Learning Algorithms cannot work with missing features therefore, missing features will always need to be taken care of. To fix missing features, you can:
1. Get rid of the whole row which has missing values in some atrribute columns,
2. Get rid of the whole attribute column entirely, or
3. Set the missing values to some values(eg. zero, mean or median of the attribute column, etc).
If Option 3 is choosen, whatever value you use should be used to replace missing values in the test set too.

Sckikit-Learn provides a handy class to  take care of missing values: SimpleImputer

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy="median")

In [ ]:
housing_num = housing.drop("ocean_proximity", axis=1)
imputer.fit(housing_num)

# Its always safe to apply the imputer to all numerical
# attributes since we are not sure there won't be any
# missing values in new data after the system goes live.

SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [ ]:
# Transform the training set by replacing missing
# values with value learned by the imputer.
X = imputer.transform(housing_num)

In [ ]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [ ]:
housing_tr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
12655,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736
15502,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373
2908,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750
14053,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264
20496,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964
...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900
12661,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139
19263,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797
19140,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964
19773,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319

To checkout: For more details on the design principles, see Lars Buitinck et al., “API Design for Machine Learning Software: Experiences from the Scikit-Learn Project;

In [ ]:
housing_cat = housing[["ocean_proximity"]]

In [ ]:
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7277
INLAND             5262
NEAR OCEAN         2124
NEAR BAY           1847
ISLAND                2
dtype: int64

Most Machine learning algorithms prefer to work with numbers so its advisable to convert categorical attributes to numbers.

This can be done using scikit-learn's OrdinalEncoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
ordinal_encoder = OrdinalEncoder()

In [ ]:
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)

In [ ]:
housing_cat_encoded_tr = pd.DataFrame(housing_cat_encoded, columns=["ocean_proximity"])

One issue with the conversion of categorical attributes to numbers is that ML algorithms will assume that two nearby values are more similar than two distant values. This may be fine in some cases such as an ordered category of "bad", "average", "good" and "excellent" but this is not always the case. To fix this issue, a common solution is to create one binary attribute per category. one attribute equal to 1 when it's value matches the category and 0 otherwise. This is called one hot encoding and scikit learn provides a OneHotEncoder class to convert categorical values into one hot vectors.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
cat_encoder = OneHotEncoder()

In [ ]:
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)

In [ ]:
housing_cat_1hot

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

If a categorical attribute has a large number of possible categories, then one-hot encoding will result in a large number of input features. This may slow down training and degrade performance. If this happens, you may want to replace the categorical input with useful numerical features related to the categories. Eg. You can replace ocean_proximity feature with the distance to the ocean. Or you can replace each category with a learnable, low-dimensional vector called an embedding. Each category's representation would be learned during training.

### Custom Transformers.

Although Scikit-Learn provides many useful transformers, you will need to write your own for tasks such as custom cleanup operations or combining specific attributes. You will want your transformer to work seamlessly with Scikit-Learn functionalities (such as pipelines), and since Scikit-Learn relies on duck typing (not inheritance), all you need to do is create a class and implement three methods: fit()(returning self ), transform() , and fit_transform().
You can get the last one for free by simply adding TransformerMixin as a base class. If you add BaseEstimator as a base class (and avoid *args and **kargs in your constructor), you will also get two extra methods ( get_params() and set_params()) that will be useful for automatic hyperparameter tuning.

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

In [ ]:
class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room=True): # no *args or **kwargs4
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # nothing else to do
    def transform(self, X):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                        bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [ ]:
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)

In [ ]:
housing_extra_attribs = attr_adder.transform(housing.values)

### Feature Scaling

With few exceptions, Machine Learning algorithms dont perform well when the input numerical attributes have very different scales therefore feature scaling needs to be applied to the datasets.
Note: Scaling the target values is generally not required.
Methods of Feature Scaling:
1. Min-Max Scaling(Normalization): Subtract the min value and divide by the (max minus the min). This rescales the values to end up ranging from 0 to 1 and can be performed using the MinMaxScaler scikit-learn Transformer.
2. Standardization: First subtract the mean value then divide by the standard deviation so the resulting distribution has unit variance.

Unlike min-max scaling, standardization does not bound values to a specific range, this may be a problem for some ml algorithms(eg. neural networks often expect an input value ranging from 0 to 1). However, standardization is much less affected by outliers and can be performed using the StandardScaler standardization.

### Transformation Pipelines

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ("attribs_adder", CombinedAttributesAdder()),
    ("std_scaler", StandardScaler()),
])

In [ ]:
housing_num_tr = num_pipeline.fit_transform(housing_num)

So far, we have handled the categorical columns and the numerical columns separately. It would be more convenient to have a single transformer able to handle all columns, applying the appropriate transformations to each column

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

In [ ]:
full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", OneHotEncoder(), cat_attribs)
])

In [ ]:
housing_prepared = full_pipeline.fit_transform(housing)

## Select and Train a Model

In [ ]:
### Training and Evaluating a training set
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)

LinearRegression()

In [ ]:
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)
print("Predictions: ", lin_reg.predict(some_data_prepared))
print("Labels: ", list(some_labels))

Predictions:  [ 84992. 305664. 152000. 186624. 244800.]
Labels:  [72100.0, 279600.0, 82700.0, 112500.0, 238300.0]

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
housing_predictions = lin_reg.predict(housing_prepared)
lin_mse = mean_squared_error(housing_labels, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

68631.75505754171

This is better than nothing but clearly not a great score: Most districts' median_housing_values range between $120000 and $265000 so a typical prediction error of $68631 is not very satisfying. This is an example of a model underfitting the data. When this happens, it can mean that the features do not provide enough information to make good predictions, or that the model is not powerful enough. To fix underfitting, one way would be to select a more powerful model, or to feed the training algorithm with better features, or to reduce the constraints on the model.

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
tree_reg = DecisionTreeRegressor()
tree_reg.fit(housing_prepared, housing_labels)

DecisionTreeRegressor()

In [ ]:
print("Predictions: ", tree_reg.predict(some_data_prepared))
print("Labels: ", list(some_labels))

Predictions:  [ 72100. 279600.  82700. 112500. 238300.]
Labels:  [72100.0, 279600.0, 82700.0, 112500.0, 238300.0]

In [ ]:
housing_predictions = tree_reg.predict(housing_prepared)
tree_mse = mean_squared_error(housing_labels, housing_predictions)
tree_rmse = np.sqrt(tree_mse)

In [ ]:
tree_rmse

0.0

This result shows that the model has no error in its predictions. This is more likely a case that the model has badly overfit the data rather than the case of the model being perfect. How can you be sure of which it is, well, you don't want to touch the test set until you are ready to launch a model you are confident about, so you need to use part of the training set for training and part of it for model validation. One way to make this evaluation would be to use the train_test_split() function to split the training set into a smaller training set and a validation set, then train your models against the smaller training set and evaluate them against the validation set. Another great alternative would be to use Scikit Learn's K-fold cross-validation feature.

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scores = cross_val_score(tree_reg, housing_prepared, housing_labels,
                        scoring="neg_mean_squared_error", cv=10)

In [ ]:
tree_rmse_scores = np.sqrt(-scores)

In [ ]:
def display_scores(scores):
    print("Scores: ", scores)
    print("Mean: ", scores.mean())
    print("Standard Deviation: ", scores.std())

In [ ]:
display_scores(tree_rmse_scores)

Scores:  [72617.65755506 70889.79980412 66966.92251681 71224.69589229
 69607.97455421 76329.41840659 70857.95742207 73215.36912339
 69129.82864172 71927.38632126]
Mean:  71276.7010237509
Standard Deviation:  2404.279223630474

In [ ]:
lin_scores = cross_val_score(lin_reg, housing_prepared, housing_labels,
                            scoring="neg_mean_squared_error", cv=10)

In [ ]:
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores:  [71785.95452886 64114.99166359 67771.17124356 68630.49425537
 66842.33585749 72530.2374193  74085.0136115  68802.33629334
 66435.54302345 70149.01820096]
Mean:  69114.70960974132
Standard Deviation:  2899.1555376564042

Building a model on top of many other models is called ensemble learning and it is often a great way to push ML algorithms even further

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
forest_reg = RandomForestRegressor()
forest_reg.fit(housing_prepared, housing_labels)

RandomForestRegressor()

In [ ]:
housing_predictions = forest_reg.predict(housing_prepared)
forest_mse = mean_squared_error(housing_labels, housing_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

18661.01807186113

In [ ]:
forest_scores = cross_val_score(forest_reg, housing_prepared, housing_labels,
                            scoring="neg_mean_squared_error", cv=10)

In [ ]:
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores:  [51529.45749921 49149.88292982 46805.76839238 51914.51811427
 47239.36158638 51757.69478352 52847.1691525  49670.40059007
 48292.94441577 53945.62907016]
Mean:  50315.28265340841
Standard Deviation:  2309.6331703583814

As seen from the results, the score on the training set is still much lower than on the validation sets, this means that the model is still overfitting the training set. Possible solutions for overfitting are to simplify the model, constrain it(i.e regularize it), or get a lot more training data).

You should save every model you experiment with so that you can come back easily to any model you want. Make sure to save both the hyperparameters and the trained parameters, as welll as the cross-validation scores and perhaps the actual predictions as well. This will alllow you to easily compare scores across model types and compare the type of errors they make.
You can easily save scikit learn models by using python's pickle module or by using the joblib library, which is more efficient at serializing large numpy arrays

## Fine-Tune Your Model

### Grid Search
One way to finetune models is to fiddle with the hyperparameters manually until you find a great combination of hyperparameter values. This would be a very tedious work and you may not have time to explore many combinations. Instead, this process can be performed using scikit-learns's GridSearchCV.

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = [
    {"n_estimators": [3, 10, 30], "max_features":
    [2, 4, 6,8]},
    {"bootstrap": [False], "n_estimators":
    [3, 10], "max_features": [2, 3, 4]}
]
forest_reg = RandomForestRegressor()
grid_search = GridSearchCV(forest_reg, param_grid,
                          cv=5, scoring="neg_mean_squared_error",
                          return_train_score=True)

grid_search.fit(housing_prepared, housing_labels)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='neg_mean_squared_error')

When you have no idea what value a hyperparameter should have, a simple approach is to try out consecutive powers of 10

In [ ]:
grid_search.best_params_

{'max_features': 8, 'n_estimators': 30}

In [ ]:
grid_search.best_estimator_

RandomForestRegressor(max_features=8, n_estimators=30)

In [ ]:
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"],
                             cvres["params"]):
    print(np.sqrt(-mean_score), params)

64432.09087186414 {'max_features': 2, 'n_estimators': 3}
55347.345869720906 {'max_features': 2, 'n_estimators': 10}
52601.24113158484 {'max_features': 2, 'n_estimators': 30}
61181.250870711294 {'max_features': 4, 'n_estimators': 3}
53181.59995625997 {'max_features': 4, 'n_estimators': 10}
50690.86385461692 {'max_features': 4, 'n_estimators': 30}
60088.92192805513 {'max_features': 6, 'n_estimators': 3}
52700.432708119544 {'max_features': 6, 'n_estimators': 10}
50260.08698404733 {'max_features': 6, 'n_estimators': 30}
59240.42774832258 {'max_features': 8, 'n_estimators': 3}
52089.222302155256 {'max_features': 8, 'n_estimators': 10}
50133.57726857818 {'max_features': 8, 'n_estimators': 30}
62849.05718874748 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
54486.11477876012 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
59994.607765481254 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
52795.52370338991 {'bootstrap': False, 'max_features': 3, 'n_estimators': 10}
58789.144490906205 {'bootstrap': False, 'max_features': 4, 'n_estimators': 3}
51662.552847229395 {'bootstrap': False, 'max_features': 4, 'n_estimators': 10}

### Randomized Search
The grid search approach is fine when you're exploring relatively few combinations but when the hyperparameter search space is large, it is often better to use RandomizedSearchCV instead. This class, instead of trying out all possible combinations, it evaluates a given number of random combinations by selellcting a random value for each hyperparameter at every iteration.

### Ensemble Methods

Another way to fine-tune your system is to try to combine the models that perform best. The group(or "ensemble") will often perform better than the individual model especially if the individual models make very different types of erros.

### Analyze the best models and their errors

In [ ]:
feature_importances = grid_search.best_estimator_.feature_importances_

In [ ]:
extra_attribs = ["rooms_per_hhold", "pop_per_hhold",
                "bedrooms_per_room"]
cat_encoder = full_pipeline.named_transformers_["cat"]
cat_one_hot_attribs = list(cat_encoder.categories_[0])
attributes = num_attribs + extra_attribs + cat_one_hot_attribs

In [ ]:
sorted(zip(feature_importances, attributes), reverse=True)

[(0.38202555448525777, 'median_income'),
 (0.1569003603534089, 'INLAND'),
 (0.10833122004985757, 'pop_per_hhold'),
 (0.06894709757598083, 'bedrooms_per_room'),
 (0.06729260171389602, 'longitude'),
 (0.05830996909205132, 'latitude'),
 (0.04497267037421643, 'housing_median_age'),
 (0.040043512042047, 'rooms_per_hhold'),
 (0.01602845743293094, 'total_rooms'),
 (0.015178909179244823, 'population'),
 (0.01457793792552465, 'total_bedrooms'),
 (0.013728466604946416, 'households'),
 (0.008584555989957332, '<1H OCEAN'),
 (0.0029341517301350417, 'NEAR OCEAN'),
 (0.002023329548111727, 'NEAR BAY'),
 (0.0001212059024332408, 'ISLAND')]

You may then want to try some of the less useful features

### Evaluate your system on the test set

Only call transform on the test data. Do not fit the test set.

In [ ]:
final_model = grid_search.best_estimator_

In [ ]:
X_test = strat_test_set.drop("median_house_value", axis=1)
y_test = strat_test_set["median_house_value"].copy()

In [ ]:
X_test_prepared = full_pipeline.transform(X_test)
final_predictions = final_model.predict(X_test_prepared)

In [ ]:
final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
final_rmse

48116.52018911176

Models tend to rot over time becase the world changes, so if the model was trained with last year's data, it may not be adapted to today's data. As such, one needs to put in place a monitoring syste to evaluate the live model as well as all the relevant processes to define what to do in case of failures and how to prepare for them.
Keep backups of every model you create and have the process and tools in place to roll back to a previous model quickly, in case the new model starts failing badly for some reason. this also makes it possible to compare new models with previous ones.Also have a backup of every version of your datasets so that you can roll back to a previous dataset if the new one ever gets corrupted

If a model performs well on the training data but generalizes poorly
according to the cross-validation metrics, then your model is overfitting. If it per‐
forms poorly on both, then it is underfitting.